apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
    traefik.docker.network: challenge1
    traefik.editor-waf.backend: editor-waf
    traefik.editor-waf.frontend.rule: Host:editor-waf.securethebox.us
    traefik.editor-waf.port: "6000"
    traefik.enable: "true"
    traefik.waf.backend: waf
    traefik.waf.frontend.rule: Host:waf.securethebox.us
    traefik.waf.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-modsecurity
  name: nginx-modsecurity
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-modsecurity
    spec:
      containers:
      - image: really/nginx-modsecurity:latest
        name: nginx-modsecurity
        resources: {}
      hostname: nginx-modsecurity
      restartPolicy: Always
status: {}
