apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
    traefik.docker.network: challenge1
    traefik.frontend.rule: Host:monitor.securethebox.us
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - image: traefik:1.7.10-alpine
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: traefik-claim0
        - mountPath: /traefik.toml
          name: traefik-claim1
        - mountPath: /acme.json
          name: traefik-claim2
      hostname: traefik
      restartPolicy: Always
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
      - name: traefik-claim2
        persistentVolumeClaim:
          claimName: traefik-claim2
status: {}
