apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: whoami.securethebox.us
    http:
      paths:
        backend:
          serviceName: whoami-service
          servicePort: http
